name: Deploy to Firebase Hosting on merge or CMS update
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [cms-update]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - run: pnpm install && pnpm build
        working-directory: ./landing-page
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AZABUNOKAZE_LP_C88F6 }}
          channelId: live
          projectId: azabunokaze-lp-c88f6
          entryPoint: ./landing-page
